apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
spec:
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: andresgalvan/products-service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JDBC_URL
              value: jdbc:postgresql://jdbc-postgres-service:5432/postgres
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: products-service
