---
name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repository
        uses: actions/checkout@v2.3.3

      - name: ☕ Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: 🛠 Build project
        run: ./gradlew build --no-daemon

      - name: Run integration tests
        run: ./gradlew cucumber --no-daemon
